detiledEthinicity: src/main/resources/shinny/shinny-artifacts/detailed-ethinicity.json
detiledRace: src/main/resources/shinny/shinny-artifacts/detailed-race.json
ombRace: src/main/resources/shinny/shinny-artifacts/omb-race.json
ombEthinicity: src/main/resources/shinny/shinny-artifacts/omb.ethinicity.json
shinnyPersonalPronouns: src/main/resources/shinny/shinny-artifacts/shinny-personal-pronouns.json
