org:
  techbd:    
    service:
      http:
        interactions:
          defaultPersistStrategy: "{ \"nature\": \"fs\" }"
          saveUserDataToInteractions: true
        hub:
          prime:
            csv:
              validation:
                pythonScriptPath: ${TECHBD_CSV_PYTHON_SCRIPT_PATH:../support/specifications/flat-file/validate-nyher-fhir-ig-equivalent.py}
                pythonExecutable: ${TECHBD_CSV_PYTHON_EXECUTABLE:python3}
                packagePath: ${TECHBD_CSV_PACKAGE_PATH:../support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json}
                inboundPath: ${TECHBD_CSV_INBOUND_PATH:/mnt/wsl/Ubuntu-22.04/tmp}/techbyDesign/flatFile/inbound
                outputPath: ${TECHBD_CSV_INBOUND_PATH:/mnt/wsl/Ubuntu-22.04/tmp}/techbyDesign/flatFile/outbound
                ingessHomePath: ${TECHBD_CSV_INGRESS_PATH:/mnt/wsl/Ubuntu-22.04/tmp}/techbyDesign/flatFile/ingress
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: actuator,beans,env,openapi,swagger-ui,health,info,metrics
  health:
    db:
      enabled: true
  endpoint:
    beans:
      enabled: true
    env:
      enabled: true
      show-values: always
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true       