name: QE Statistics Notification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send-email:
    runs-on: techbd-sql

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .pgpass file
        run: |
          # Write the metadata comment to the .pgpass file
          echo "# { id: \"PROD_TECHBD_UDI_DS_PRIME\", description: \"UDI Prime database\", boundary: \"Production\" }" > ~/.pgpass

          # Append the database connection details to the .pgpass file
          echo "${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PASSWORD }}" >> ~/.pgpass

          # Set the .pgpass file permissions to 600 (read and write for owner only)
          chmod 600 ~/.pgpass

      - name: Fetch combined data from PostgreSQL
        id: fetch-data-combined
        run: |
          DATA=$(psql -h ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }} \
                      -p ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }} \
                      -U ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }} \
                      -d ${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }} \
                      -c "SELECT SUM(qe_fhir_submission_count) AS tenant_submission_count, SUM(qe_fhir_pass_count) AS tenant_pass_count, SUM(qe_fhir_fail_count) AS tenant_fail_count, SUM(qe_fhir_pass_count + qe_fhir_fail_count) AS overall_response_count FROM techbd_udi_ingress.fhir_tenant_stats_view as ftsv" \
                      --no-align --tuples-only)
          echo "combined_data=${DATA}" >> $GITHUB_ENV
     
      - name: Format fetched data combined
        id: format-data-combined
        run: |
          IFS='|' read -r tenant_submission_count tenant_pass_count tenant_fail_count overall_response_count <<< "${{ env.combined_data }}"
          echo "formatted_combined_data<<EOF" >> $GITHUB_ENV
          echo "Combined QE FHIR Submission Statistics:" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "- Total Submissions: $tenant_submission_count" >> $GITHUB_ENV
          echo "- Passed Submissions: $tenant_pass_count" >> $GITHUB_ENV
          echo "- Failed Submissions: $tenant_fail_count" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          username: ${{ secrets.SES_SMTP_USERNAME }}
          password: ${{ secrets.SES_SMTP_PASSWORD }}
          subject: "Daily Tech by Design QE Statistics Notification"
          body: |
              The following are the QE FHIR Submission Statistics for the day:
          
              ${{ env.formatted_combined_data }}
          content_type: "text/html"
          from: "Tech by Design QE Statistics Notification <no-reply@tx.techbd.org>"
          to: alan-francis@netspective.in
