name: UDI Prime RDS schema generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .pgpass file
        run: |
          # Write the metadata comment to the .pgpass file
          echo "# { id: \"PROD_TECHBD_UDI_DS_PRIME\", description: \"UDI Prime database \", boundary: \"Production\" }" > ~/.pgpass

          # Append the database connection details to the .pgpass file
          echo "${{ secrets.PROD_TECHBD_UDI_DS_PRIME_HOST }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PORT }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_NAME }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_USER }}:${{ secrets.PROD_TECHBD_UDI_DS_PRIME_PASSWORD }}" >> ~/.pgpass

          # Set the .pgpass file permissions to 600 (read and write for owner only)
          chmod 600 ~/.pgpass

      - name: Clone Polyglot Prime repository
        run: git clone https://github.com/tech-by-design/polyglot-prime.git

      - name: Navigate to UDI Prime and Generate SQL
        run: |
          cd polyglot-prime/udi-prime
          ./udictl.ts ic generate sql 

      - name: Run Migrations
        run: |
          cd polyglot-prime/udi-prime
          ./udictl.ts ic migrate --conn-id PROD_TECHBD_UDI_DS_PRIME

      - name: Run test
        run: |
          cd polyglot-prime/udi-prime
          ./udictl.ts ic test --conn-id PROD_TECHBD_UDI_DS_PRIME
