org:
  techbd:
    csv:
      validation:
        pythonScriptPath: ../support/specifications/flat-file/validate-nyher-fhir-ig-equivalent.py
        pythonExecutable: python3
        packagePath: ../support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json
        inboundPath: /mnt/wsl/Ubuntu-22.04/tmp}/techbyDesign/flatFile/inbound
        outputPath: /mnt/wsl/Ubuntu-22.04/tmp}/techbyDesign/flatFile/outbound
        ingessHomePath: /mnt/wsl/Ubuntu-22.04/tmp}/techbyDesign/flatFile/ingress 