org:
    techbd:
        defaultDatalakeApiUrl: https://qa.hrsn.nyehealth.org/HRSNBundle
        defaultDataLakeApiAuthn:
            mTlsStrategy: aws-secrets
            mTlsAwsSecrets: 
                mTlsKeySecretName: techbd-qa-client-key
                mTlsCertSecretName: techbd-qa-client-certificate
        dataLedgerApiUrl: https://k77kvhgmkh.execute-api.us-east-1.amazonaws.com/qa
        dataLedgerTracking: true
        dataLedgerDiagnostics: true
        dataLedgerApiKeySecretName: techbd-nyec-dataledger-api-key