org:
  techbd:
    csv:
        validation:
            pythonScriptPath: ../support/specifications/flat-file/validate-nyher-fhir-ig-equivalent.py
            pythonExecutable: python3
            packagePath: ../support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json
            inboundPath: /app/techbyDesign/flatFile/inbound
            outputPath: /app/techbyDesign/flatFile/outbound
            ingressHomePath: /app/techbyDesign/flatFile/ingress