org:
    techbd:
        defaultDatalakeApiUrl: https://qa.hrsn.nyehealth.org/HRSNBundle
        defaultDataLakeApiAuthn:
            mTlsStrategy: aws-secrets
            mTlsAwsSecrets: 
                mTlsKeySecretName: techbd-qa-client-key
                mTlsCertSecretName: techbd-qa-client-certificate
        dataLedgerApiUrl: https://zq34s8hsvh.execute-api.us-east-1.amazonaws.com/qa/DataLedger
        dataLedgerTracking: true
        dataLedgerDiagnostics: true
        dataLedgerApiKeySecretName: techbd-nyec-dataledger-api-key
    csv:
      validation:
        pythonScriptPath: ../support/specifications/flat-file/validate-nyher-fhir-ig-equivalent.py
        pythonExecutable: python3
        packagePath: ../support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json
        inboundPath: /app/techbyDesign/flatFile/inbound
        outputPath: /app/techbyDesign/flatFile/outbound
        ingessHomePath: /app/techbyDesign/flatFile/ingress         